
#include "BinaryMetadataExtractor.h"
#include "FilesystemMetadataExtractor.h"
#include <google/protobuf/descriptor.pb.h>
#include <google/protobuf/dynamic_message.h>
#include <google/protobuf/io/coded_stream.h>
#include <boost/filesystem/operations.hpp>
#include <fstream>
#include <iostream>
#include <unordered_map>

bool ParseFromCodedInputStreamWithDescriptorPool(google::protobuf::FileDescriptorProto& proto, google::protobuf::io::CodedInputStream* decoder)
{
    decoder->SetExtensionRegistry(google::protobuf::DescriptorPool::generated_pool(), google::protobuf::MessageFactory::generated_factory());
    return proto.ParseFromCodedStream(decoder) && decoder->ConsumedEntireMessage();
}

std::unordered_map<std::string, std::pair<google::protobuf::FileDescriptor const*, bool>> fileDescriptorsByName;
google::protobuf::DynamicMessageFactory* dynamicMessageFactory = new google::protobuf::DynamicMessageFactory(); // LEAKED ON PURPOSE, messages generated by this are double registered (and would be double freed)

int main(int argc, char* argv[])
{
    // initialize Descriptor descriptors
    google::protobuf::DescriptorProto().GetMetadata();

    // first collect files
    std::unique_ptr<MetadataExtractor> extractor;
    if (argc > 1)
    {
        // parse protobuf metadata from binary
        extractor = std::make_unique<BinaryMetadataExtractor>();
        extractor->Parse(argv[1]);
    }
    else
    {
        extractor = std::make_unique<FilesystemMetadataExtractor>();
        extractor->Parse(boost::filesystem::current_path());
    }

    if (extractor->GetMetadata().empty())
    {
        std::cout << "No .proto descriptors found" << std::endl;
        return 1;
    }

    // its time to hack private members
    google::protobuf::DescriptorPool* pool = google::protobuf::DescriptorPool::internal_generated_pool();
    void* mutex_ = *reinterpret_cast<char**>(pool);
    void* fallback_database_ = *(reinterpret_cast<void**>(pool) + 1);
    *reinterpret_cast<void**>(pool) = nullptr; // mutex_
    *(reinterpret_cast<void**>(pool) + 1) = nullptr; // fallback_database_

    std::set<std::string> parsedFilenames;
    std::set<std::string> parsedIds;
    std::list<std::string> parsedSorted;
    // then load everything into descriptor pool
    for (size_t i = 0; i < extractor->GetMetadata().size(); ++i)
    {
        for (std::unique_ptr<MetadataExtractor::Metadata> const& meta : extractor->GetMetadata())
        {
            if (parsedIds.count(meta->GetId()))
                continue;

            std::shared_ptr<google::protobuf::io::CodedInputStream> in = meta->CreateCodedInputStream();
            if (!in)
                continue;

            google::protobuf::FileDescriptorProto fileDescProto;
            bool parseOk = false;
            try
            {
                parseOk = ParseFromCodedInputStreamWithDescriptorPool(fileDescProto, in.get());
            }
            catch (...)
            {
                continue;
            }

            for (std::string const& dependency : fileDescProto.dependency())
            {
                parseOk = parsedFilenames.count(dependency);
                if (!parseOk)
                    break;
            }

            if (parseOk)
            {
                if (fileDescProto.name() == "google/protobuf/descriptor.proto")
                {
                    parsedFilenames.insert(fileDescProto.name());
                    continue;
                }

                fileDescProto.mutable_options()->set_optimize_for(google::protobuf::FileOptions_OptimizeMode_CODE_SIZE);
                if (google::protobuf::FileDescriptor const* fileDesc = pool->BuildFile(fileDescProto))
                {
                    auto fd = fileDescriptorsByName.try_emplace(fileDesc->name(), fileDesc, false);
                    if (fd.second)
                    {
                        if (fileDesc->name() != "google/protobuf/descriptor.proto")
                        {
                            google::protobuf::MessageFactory::InternalRegisterGeneratedFile(fd.first->first.c_str(), [](std::string const& name)
                            {
                                std::pair<google::protobuf::FileDescriptor const*, bool>& p = fileDescriptorsByName[name];
                                if (p.second)
                                    return;

                                p.second = true;
                                google::protobuf::FileDescriptor const* desc = p.first;
                                for (int j = 0; j < desc->message_type_count(); ++j)
                                    google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(desc->message_type(j), dynamicMessageFactory->GetPrototype(desc->message_type(j)));
                            });
                        }
                        else
                            for (int j = 0; j < fileDesc->message_type_count(); ++j)
                                google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(fileDesc->message_type(j), dynamicMessageFactory->GetPrototype(fileDesc->message_type(j)));
                    }

                    for (int j = 0; j < fileDesc->extension_count(); ++j)
                    {
                        google::protobuf::FieldDescriptor const* extension = fileDesc->extension(j);
                        switch (extension->type())
                        {
                            case google::protobuf::FieldDescriptor::Type::TYPE_ENUM:
                                google::protobuf::internal::ExtensionSet::RegisterEnumExtension(
                                    google::protobuf::MessageFactory::generated_factory()->GetPrototype(extension->containing_type()),
                                    extension->number(),
                                    extension->type(),
                                    extension->is_repeated(),
                                    extension->is_packed(),
                                    [](int){ return true; });
                                break;
                            case google::protobuf::FieldDescriptor::Type::TYPE_MESSAGE:
                            case google::protobuf::FieldDescriptor::Type::TYPE_GROUP:
                                google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
                                    google::protobuf::MessageFactory::generated_factory()->GetPrototype(extension->containing_type()),
                                    extension->number(),
                                    extension->type(),
                                    extension->is_repeated(),
                                    extension->is_packed(),
                                    google::protobuf::MessageFactory::generated_factory()->GetPrototype(extension->message_type()));
                                break;
                            default:
                                google::protobuf::internal::ExtensionSet::RegisterExtension(
                                    google::protobuf::MessageFactory::generated_factory()->GetPrototype(extension->containing_type()),
                                    extension->number(),
                                    extension->type(),
                                    extension->is_repeated(),
                                    extension->is_packed());
                                break;
                        }
                    }

                    parsedFilenames.insert(fileDesc->name());
                    parsedIds.insert(meta->GetId());
                    if (fileDesc->name() != "google/protobuf/descriptor.proto")
                        parsedSorted.push_back(meta->GetId());
                    else
                        parsedSorted.push_front(meta->GetId());

                    {
                        boost::filesystem::path parentPath = boost::filesystem::path(fileDesc->name()).parent_path();
                        if (!parentPath.empty())
                            boost::filesystem::create_directories(parentPath);
                        std::ofstream f(fileDesc->name());
                        f << fileDesc->DebugString() << std::endl;
                        f.close();
                    }
                }
            }
        }
    }

    // unhack to free memory
    *reinterpret_cast<void**>(pool) = mutex_;
    *(reinterpret_cast<void**>(pool) + 1) = fallback_database_;

    google::protobuf::ShutdownProtobufLibrary();

    return 0;
}
